/**
 * main.js — 3D Tiles Point Cloud Viewer
 *
 * Loads a 3D Tiles tileset (generated by py3dtiles from LAS data) and renders
 * it using Three.js + NASA AMMOS 3d-tiles-renderer. Supports ECEF and local
 * coordinate systems, vertex-coloured point clouds, orbit controls, first-
 * person cave exploration mode, and a simple HTML UI overlay.
 */

import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { PointerLockControls } from 'three/examples/jsm/controls/PointerLockControls.js';
import { TilesRenderer } from '3d-tiles-renderer';

// ─── Constants ───────────────────────────────────────────────────────────────

const TILESET_URL = '/tileset/tileset.json';

/**
 * Radius of the Earth in metres — used to detect ECEF bounding spheres.
 * Any bounding-sphere centre whose magnitude is in [0.5 R, 2 R] is treated
 * as ECEF.
 */
const EARTH_RADIUS = 6_371_000;

// ─── Scene setup ─────────────────────────────────────────────────────────────

const container = document.getElementById('canvas-container');

const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setPixelRatio(window.devicePixelRatio);
renderer.setSize(container.clientWidth, container.clientHeight);
container.appendChild(renderer.domElement);

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x1a1a2e);

const camera = new THREE.PerspectiveCamera(
  60,
  container.clientWidth / container.clientHeight,
  0.1,
  1e8,
);
camera.position.set(0, 0, 100);

const clock = new THREE.Clock();

// ─── Tiles renderer ───────────────────────────────────────────────────────────

const tilesRenderer = new TilesRenderer(TILESET_URL);
tilesRenderer.setCamera(camera);
tilesRenderer.setResolutionFromRenderer(camera, renderer);
scene.add(tilesRenderer.group);

// ─── State ───────────────────────────────────────────────────────────────────

let pointSize = 0.05;
let moveSpeed = 5.0;
let tilesetLoaded = false;
let darkBackground = true;

/** @type {'orbit' | 'fps'} */
let currentMode = 'orbit';

/** Keyboard state for FPS movement */
const keys = {};

/** Cached bounding sphere centre + radius for entry positioning */
let tilesetSphere = new THREE.Sphere();

// ─── Controls ─────────────────────────────────────────────────────────────────

/**
 * Sets up OrbitControls for the default viewing mode.
 * @returns {OrbitControls}
 */
function setupOrbitControls() {
  const oc = new OrbitControls(camera, renderer.domElement);
  oc.enableDamping = true;
  oc.dampingFactor = 0.08;
  oc.screenSpacePanning = true;
  return oc;
}

/**
 * Sets up PointerLockControls for the first-person explorer mode.
 * @returns {PointerLockControls}
 */
function setupFPSControls() {
  const plc = new PointerLockControls(camera, renderer.domElement);

  plc.addEventListener('lock', () => {
    lockHint.classList.remove('visible');
    crosshair.classList.add('visible');
  });

  plc.addEventListener('unlock', () => {
    crosshair.classList.remove('visible');
    // If still in FPS mode, show the lock hint again
    if (currentMode === 'fps') {
      lockHint.classList.add('visible');
    }
  });

  return plc;
}

const orbitControls = setupOrbitControls();

// Grab DOM refs for FPS UI elements now, before setupFPSControls uses them
const crosshair = document.getElementById('crosshair');
const lockHint = document.getElementById('lock-hint');
const controlsHintEl = document.getElementById('controls-hint');

const fpsControls = setupFPSControls();

// ─── Mode switching ───────────────────────────────────────────────────────────

const modeIndicator = document.getElementById('mode-indicator');
const enterCaveBtn = document.getElementById('enter-cave');

/**
 * Switches between orbit and FPS explorer modes.
 * @param {'orbit' | 'fps'} mode
 */
function setMode(mode) {
  currentMode = mode;

  if (mode === 'fps') {
    orbitControls.enabled = false;
    enterCaveBtn.classList.add('hidden');
    modeIndicator.textContent = '\ud83d\udeb6 Explorer';

    // Position camera at bounding sphere edge, looking toward centre
    enterFPSMode();

    // Show lock hint — pointer will lock on next click
    lockHint.classList.add('visible');

    // Show controls hint for 5 seconds
    showControlsHint();
  } else {
    orbitControls.enabled = true;
    enterCaveBtn.classList.remove('hidden');
    modeIndicator.textContent = '\ud83d\udd2d Orbit';

    // Unlock pointer if still locked
    if (fpsControls.isLocked) fpsControls.unlock();
    lockHint.classList.remove('visible');
    crosshair.classList.remove('visible');
    controlsHintEl.classList.remove('visible');

    // Snap orbit target to current camera look-at direction
    const forward = new THREE.Vector3();
    camera.getWorldDirection(forward);
    orbitControls.target.copy(camera.position).addScaledVector(forward, tilesetSphere.radius || 10);
    orbitControls.update();
  }
}

/**
 * Positions the camera at the bounding sphere edge for FPS entry.
 */
function enterFPSMode() {
  if (tilesetSphere.radius <= 0) return;

  camera.position.set(
    tilesetSphere.center.x + tilesetSphere.radius,
    tilesetSphere.center.y,
    tilesetSphere.center.z,
  );
  camera.lookAt(tilesetSphere.center);
}

/**
 * Shows the controls hint overlay, then fades it after 5 seconds.
 */
function showControlsHint() {
  controlsHintEl.classList.remove('fade-out');
  controlsHintEl.classList.add('visible');
  setTimeout(() => controlsHintEl.classList.add('fade-out'), 4400);
  setTimeout(() => controlsHintEl.classList.remove('visible', 'fade-out'), 5000);
}

// "Enter Cave" button
enterCaveBtn.addEventListener('click', () => setMode('fps'));

// Press E to enter FPS mode
document.addEventListener('keydown', (e) => {
  if (e.code === 'KeyE' && currentMode === 'orbit') {
    setMode('fps');
  }
});

// Click to lock pointer when in FPS mode
renderer.domElement.addEventListener('click', () => {
  if (currentMode === 'fps' && !fpsControls.isLocked) {
    fpsControls.lock();
  }
});

// Escape exits FPS mode (PointerLockControls fires 'unlock' on Esc automatically)
fpsControls.addEventListener('unlock', () => {
  if (currentMode === 'fps') {
    setMode('orbit');
  }
});

// ─── FPS movement ─────────────────────────────────────────────────────────────

document.addEventListener('keydown', (e) => { keys[e.code] = true; });
document.addEventListener('keyup', (e) => { keys[e.code] = false; });

/**
 * Processes WASD + Space/Shift movement for FPS mode. Called every frame.
 * @param {number} delta — seconds since last frame
 */
function updateFPSMovement(delta) {
  if (currentMode !== 'fps' || !fpsControls.isLocked) return;

  const speed = moveSpeed * delta;

  if (keys['KeyW'] || keys['ArrowUp']) fpsControls.moveForward(speed);
  if (keys['KeyS'] || keys['ArrowDown']) fpsControls.moveForward(-speed);
  if (keys['KeyA'] || keys['ArrowLeft']) fpsControls.moveRight(-speed);
  if (keys['KeyD'] || keys['ArrowRight']) fpsControls.moveRight(speed);
  if (keys['Space']) camera.position.y += speed;
  if (keys['ShiftLeft'] || keys['ShiftRight']) camera.position.y -= speed;
}

// ─── UI ───────────────────────────────────────────────────────────────────────

/**
 * Wires up all HTML overlay interactions and returns helper setters that the
 * rest of main.js can call to push runtime values into the UI.
 *
 * @returns {{
 *   setLoadingProgress: (loaded: number, total: number) => void,
 *   hideLoading: () => void,
 *   setTilesetInfo: (center: THREE.Vector3, radius: number, isECEF: boolean) => void,
 *   showError: (message?: string) => void,
 * }}
 */
function createUI() {
  const pointSizeSlider = /** @type {HTMLInputElement} */ (document.getElementById('point-size'));
  const pointSizeValue = document.getElementById('point-size-value');
  const moveSpeedSlider = /** @type {HTMLInputElement} */ (document.getElementById('move-speed'));
  const moveSpeedValue = document.getElementById('move-speed-value');
  const bgToggle = document.getElementById('bg-toggle');
  const loadingEl = document.getElementById('loading');
  const infoCenter = document.getElementById('info-center');
  const infoRadius = document.getElementById('info-radius');
  const infoCoords = document.getElementById('info-coords');
  const errorOverlay = document.getElementById('error-overlay');
  const errorMessage = document.getElementById('error-message');

  // Point size slider
  pointSizeSlider.addEventListener('input', () => {
    pointSize = parseFloat(pointSizeSlider.value);
    pointSizeValue.textContent = pointSize.toFixed(2);
    applyPointSizeToScene(pointSize);
  });

  // Move speed slider
  moveSpeedSlider.addEventListener('input', () => {
    moveSpeed = parseFloat(moveSpeedSlider.value);
    moveSpeedValue.textContent = moveSpeed.toFixed(1);
  });

  // Background toggle
  bgToggle.addEventListener('click', () => {
    darkBackground = !darkBackground;
    scene.background = new THREE.Color(darkBackground ? 0x1a1a2e : 0xf0f0f8);
    document.body.style.background = darkBackground ? '#1a1a2e' : '#f0f0f8';
  });

  return {
    setLoadingProgress(loaded, total) {
      if (total === 0) {
        loadingEl.textContent = 'Waiting for tiles\u2026';
      } else {
        loadingEl.textContent = `Loading tiles: ${loaded} / ${total}`;
      }
      loadingEl.classList.remove('hidden');
    },

    hideLoading() {
      loadingEl.classList.add('hidden');
    },

    setTilesetInfo(center, radius, isECEF) {
      if (isECEF) {
        // Convert ECEF to approximate lat/lon for display
        const lat = THREE.MathUtils.radToDeg(
          Math.atan2(center.z, Math.sqrt(center.x ** 2 + center.y ** 2)),
        );
        const lon = THREE.MathUtils.radToDeg(Math.atan2(center.y, center.x));
        infoCenter.textContent = `${lat.toFixed(4)}\u00b0, ${lon.toFixed(4)}\u00b0`;
      } else {
        infoCenter.textContent =
          `${center.x.toFixed(2)}, ${center.y.toFixed(2)}, ${center.z.toFixed(2)}`;
      }
      infoRadius.textContent = radius > 1000
        ? `${(radius / 1000).toFixed(2)} km`
        : `${radius.toFixed(2)} m`;
      infoCoords.textContent = isECEF ? 'ECEF (geocentric)' : 'Local / projected';
    },

    showError(message) {
      if (message) errorMessage.innerHTML = message;
      errorOverlay.classList.add('visible');
    },
  };
}

const ui = createUI();

// ─── Tile model post-processing ───────────────────────────────────────────────

/**
 * Called for every tile scene that finishes loading. Finds all Points objects
 * and upgrades their material to one that uses vertex colours and size
 * attenuation.
 *
 * @param {{ scene: THREE.Object3D }} event
 */
function onTileLoad({ scene: tileScene }) {
  tileScene.traverse((obj) => {
    if (!(obj instanceof THREE.Points)) return;

    obj.material = new THREE.PointsMaterial({
      vertexColors: true,
      sizeAttenuation: true,
      size: pointSize,
    });

    // Ensure the geometry has a colour attribute; if the LAS RGB is stored
    // as 'color' (lower-case) some loaders may name it differently.
    const geo = obj.geometry;
    if (!geo.attributes.color && geo.attributes.COLOR_0) {
      geo.attributes.color = geo.attributes.COLOR_0;
    }
  });
}

tilesRenderer.addEventListener('load-model', onTileLoad);

// ─── Error handling ───────────────────────────────────────────────────────────

/**
 * Pre-flight check: fetch tileset.json before handing it to TilesRenderer so
 * we can surface a friendly error message on 404 / network failure.
 * (3d-tiles-renderer v0.3.x does not emit a load-error event.)
 */
(async function checkTilesetAvailable() {
  try {
    const res = await fetch(TILESET_URL, { method: 'HEAD' });
    if (!res.ok) {
      ui.showError(
        `Server returned <strong>${res.status} ${res.statusText}</strong> for
        <code>${TILESET_URL}</code>.<br /><br />
        Make sure your tileset files are in <code>public/tileset/</code> and
        the Vite dev server is running (<code>npm run dev</code>).`,
      );
    }
  } catch (err) {
    console.error('[preflight] fetch failed', err);
    ui.showError(
      `Could not reach <code>${TILESET_URL}</code>.<br /><br />
      Make sure the Vite dev server is running (<code>npm run dev</code>)
      and your tileset files are in <code>public/tileset/</code>.<br /><br />
      <strong>Note:</strong> Opening via <code>file://</code> will not work
      due to CORS restrictions \u2014 always use the dev server.`,
    );
  }
}());

// ─── Camera fit ───────────────────────────────────────────────────────────────

/**
 * Positions the camera so the entire tileset bounding sphere is visible.
 * Handles both local coordinate systems and large ECEF coordinates.
 *
 * @param {TilesRenderer} tiles
 */
function fitCameraToTileset(tiles) {
  const sphere = new THREE.Sphere();
  const box = new THREE.Box3();

  // getBoundingBox populates in tileset-local space
  if (!tiles.getBoundingBox(box)) {
    console.warn('[fitCamera] no bounding box available yet');
    return;
  }
  box.getBoundingSphere(sphere);

  const center = sphere.center.clone();
  const radius = sphere.radius;

  // Cache for FPS entry positioning
  tilesetSphere.copy(sphere);

  // Detect ECEF: bounding-sphere centre magnitude ~ Earth radius
  const mag = center.length();
  const isECEF = mag > EARTH_RADIUS * 0.5 && mag < EARTH_RADIUS * 2.5;

  console.group('[fitCamera] tileset bounds');
  console.log('box min:', box.min);
  console.log('box max:', box.max);
  console.log('sphere centre:', center);
  console.log('sphere radius:', radius);
  console.log('ECEF detected:', isECEF);
  console.groupEnd();

  ui.setTilesetInfo(center, radius, isECEF);

  // Place camera at 2.5x bounding sphere radius away from centre
  const distance = radius * 2.5;
  const offset = new THREE.Vector3(0, 0, distance);

  if (isECEF) {
    // For ECEF, align the camera "up" direction with the local surface normal
    const surfaceNormal = center.clone().normalize();
    const perpendicular = new THREE.Vector3()
      .crossVectors(surfaceNormal, new THREE.Vector3(0, 1, 0))
      .normalize();
    if (perpendicular.lengthSq() < 0.001) {
      perpendicular.set(1, 0, 0);
    }
    camera.position.copy(center).addScaledVector(surfaceNormal, distance);
    camera.up.copy(surfaceNormal);
  } else {
    camera.position.copy(center).add(offset);
    camera.up.set(0, 1, 0);
  }

  camera.near = radius * 0.001;
  camera.far = radius * 100;
  camera.updateProjectionMatrix();

  orbitControls.target.copy(center);
  orbitControls.minDistance = radius * 0.05;
  orbitControls.maxDistance = radius * 50;
  orbitControls.update();

  tilesetLoaded = true;
}

// Wire up tileset-ready event
tilesRenderer.addEventListener('load-tile-set', () => {
  fitCameraToTileset(tilesRenderer);
});

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Walks the scene graph and updates the size on every PointsMaterial.
 *
 * @param {number} size
 */
function applyPointSizeToScene(size) {
  scene.traverse((obj) => {
    if (obj instanceof THREE.Points && obj.material instanceof THREE.PointsMaterial) {
      obj.material.size = size;
      obj.material.needsUpdate = true;
    }
  });
}

// ─── FPS counter ─────────────────────────────────────────────────────────────

const fpsEl = document.getElementById('fps');
let lastTime = performance.now();
let frameCount = 0;

function updateFPS() {
  frameCount++;
  const now = performance.now();
  const delta = now - lastTime;
  if (delta >= 500) {
    fpsEl.textContent = `${Math.round((frameCount * 1000) / delta)} FPS`;
    frameCount = 0;
    lastTime = now;
  }
}

// ─── Loading progress ─────────────────────────────────────────────────────────

function updateLoadingProgress() {
  const stats = tilesRenderer.stats;
  const loaded = stats.loadedTiles ?? 0;
  const total = (stats.loadedTiles ?? 0) + (stats.loadingTiles ?? 0);

  if (!tilesetLoaded || (stats.loadingTiles ?? 0) > 0) {
    ui.setLoadingProgress(loaded, total);
  } else {
    ui.hideLoading();
  }
}

// ─── Resize handler ───────────────────────────────────────────────────────────

window.addEventListener('resize', () => {
  const w = container.clientWidth;
  const h = container.clientHeight;
  camera.aspect = w / h;
  camera.updateProjectionMatrix();
  renderer.setSize(w, h);
  tilesRenderer.setResolutionFromRenderer(camera, renderer);
});

// ─── Animate loop ─────────────────────────────────────────────────────────────

function animate() {
  requestAnimationFrame(animate);

  const delta = clock.getDelta();

  if (currentMode === 'orbit') {
    orbitControls.update();
  } else {
    updateFPSMovement(delta);
  }

  tilesRenderer.update();
  renderer.render(scene, camera);

  updateFPS();
  updateLoadingProgress();
}

animate();
